### PR TITLE
Improve param validation rules.

### PR DESCRIPTION
**Pull request by jsmpereira**

### CODE REVIEW

**Comment by jsmpereira** [comment]
@ct-clearhaus :eyes:

**Comment by ct-clearhaus** [comment]
:+1:

**Comment by ct-clearhaus** [comment]
http://thatsgonnabejustawesomethatyoucanhaveaveryveryverylongurlalthoughnobodymayevertypeitcorrect.ly :+1:

**Comment by jsmpereira** [comment]
Ahaha

**Comment by ct-clearhaus** [comment]
Notice that

```
% echo -n http://thatsgonnabejustawesomethatyoucanhaveaveryveryverylongurlalthoughnobodymayevertypeitcorrect.ly | wc -c
101
```

:smiley:

**Pull request merged**
